const SOURCES={
  loto6:{base:"https://www.mizuhobank.co.jp/takarakuji/apl/txt/loto6/",max:43,pick:6,bonus:1},
  loto7:{base:"https://www.mizuhobank.co.jp/takarakuji/apl/txt/loto7/",max:37,pick:7,bonus:2}
};
function normalizeDate(v){const m=String(v||"").match(/(20\d{2})\D+(\d{1,2})\D+(\d{1,2})/);return m?`${m[1]}-${m[2].padStart(2,"0")}-${m[3].padStart(2,"0")}`:""}
function decodeBuffer(buffer){const b=new Uint8Array(buffer),a=[];for(const e of ["shift_jis","utf-8"]){try{a.push(new TextDecoder(e).decode(b))}catch{}}return a.sort((x,y)=>(y.match(/ロト|本数字|ボーナス|抽せん/g)||[]).length-(x.match(/ロト|本数字|ボーナス|抽せん/g)||[]).length)[0]||""}
function cells(s){return String(s||"").split(/[,\t]/).map(x=>x.trim().replace(/^"|"$/g,""))}
function numsFrom(s,max){return cells(s).flatMap(x=>(x.match(/\d{1,2}/g)||[]).map(Number)).filter(n=>n>=1&&n<=max)}
function valid(d,c){return d&&Number.isInteger(d.no)&&d.no>0&&/^\d{4}-\d{2}-\d{2}$/.test(d.date)&&d.nums?.length===c.pick&&new Set(d.nums).size===c.pick&&d.bonus?.length===c.bonus&&new Set(d.bonus).size===c.bonus&&![...d.bonus].some(n=>d.nums.includes(n))}
function parseCsv(text,filename,c){const n=String(text||"").replace(/\r/g,""),lines=n.split("\n").map(x=>x.trim()).filter(Boolean);const no=Number((n.match(/第\s*(\d+)\s*回/)||[])[1]||(filename.match(/(\d{4})\.CSV$/i)||[])[1]||0);const date=normalizeDate(lines.find(x=>/抽せん日|抽選日|日付/.test(x))||n);let nums=[],bonus=[];for(let i=0;i<lines.length;i++){if(/本数字/.test(lines[i])){nums=numsFrom(lines[i].replace(/^.*?本数字/,""),c.max);if(nums.length<c.pick&&lines[i+1])nums.push(...numsFrom(lines[i+1],c.max));nums=nums.slice(0,c.pick)}if(/ボーナス/.test(lines[i])){bonus=numsFrom(lines[i].replace(/^.*?ボーナス(?:数字)?/,""),c.max);if(bonus.length<c.bonus&&lines[i+1])bonus.push(...numsFrom(lines[i+1],c.max));bonus=bonus.slice(0,c.bonus)}}const flat=cells(n.replace(/\n/g,","));if(nums.length!==c.pick){const i=flat.findIndex(x=>/本数字/.test(x));if(i>=0)nums=flat.slice(i+1).flatMap(x=>(x.match(/^\d{1,2}$/)||[]).map(Number)).filter(x=>x>=1&&x<=c.max).slice(0,c.pick)}if(bonus.length!==c.bonus){const i=flat.findIndex(x=>/ボーナス/.test(x));if(i>=0)bonus=flat.slice(i+1).flatMap(x=>(x.match(/^\d{1,2}$/)||[]).map(Number)).filter(x=>x>=1&&x<=c.max).slice(0,c.bonus)}const d={no,date,nums:nums.sort((a,b)=>a-b),bonus:bonus.sort((a,b)=>a-b)};if(!valid(d,c))throw new Error(`公式CSV解析失敗: ${filename}`);return d}
async function get(url){const r=await fetch(url,{cache:"no-store",headers:{"User-Agent":"Mozilla/5.0","Accept":"text/plain,text/csv,*/*"}});if(!r.ok)throw new Error(`公式サイト HTTP ${r.status}`);return r}
module.exports=async(req,res)=>{res.setHeader("Cache-Control","no-store");const game=String(req.query?.game||"loto6"),c=SOURCES[game];if(!c)return res.status(400).json({ok:false,error:"未対応ゲーム"});try{const nr=await get(c.base+"name.txt");const nt=decodeBuffer(await nr.arrayBuffer());const files=[...new Set((nt.match(/[A-Z]\d+\.CSV/gi)||[]))].sort((a,b)=>Number((b.match(/(\d{4})\.CSV$/i)||[])[1]||0)-Number((a.match(/(\d{4})\.CSV$/i)||[])[1]||0));if(!files.length)throw new Error("公式CSV一覧を解析できません");let last;for(const f of files.slice(0,5)){try{const cr=await get(c.base+f);const d=parseCsv(decodeBuffer(await cr.arrayBuffer()),f,c);return res.status(200).json({ok:true,game,draw:{...d,verified:true,source:"みずほ銀行公式CSV"},source:"みずほ銀行公式CSV",filename:f,checkedAt:new Date().toISOString()})}catch(e){last=e}}throw last||new Error("公式CSV取得失敗")}catch(e){return res.status(502).json({ok:false,game,error:String(e.message||e),checkedAt:new Date().toISOString()})}};
