'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],fmt=n=>String(n).padStart(2,'0');
const SPECS={loto6:{name:'ロト6',max:43,k:6,b:1,file:'loto6_data.csv',official:'https://www.mizuhobank.co.jp/takarakuji/check/loto/loto6/index.html',sum:[100,175],sumSoft:[85,190],high:32,zones:[[1,10],[11,21],[22,32],[33,43]]},loto7:{name:'ロト7',max:37,k:7,b:2,file:'loto7_data.csv',official:'https://www.mizuhobank.co.jp/takarakuji/check/loto/loto7/index.html',sum:[105,165],sumSoft:[95,175],high:32,zones:[[1,9],[10,19],[20,29],[30,37]]}};
const FN={odd:'偶奇バランス',sum:'合計値',con:'連番0〜1組',tail:'末尾重複1〜2',zones:'ゾーン分散',overlap:'前回重複0〜2',slide:'スライド1〜3',hot:'直近20回頻度',high:'高数字を含む',cold:'長期未出現を少量許容'};
const DEFAULT_ON={odd:true,sum:true,con:true,tail:true,zones:true,overlap:true,slide:true,hot:true,high:true,cold:true};
const DEFAULT_W={odd:18,sum:18,con:13,tail:9,zones:12,overlap:8,slide:8,hot:2,high:5,cold:4};
let game=localStorage.getItem('loto-game')||'loto7',base={},rows=[],sets=[],scores=[],stopBT=false;

const API_STORAGE='loto-auto-api-url';
function apiBase(){return (localStorage.getItem(API_STORAGE)||'').replace(/\/$/,'')}
function validateDraw(x,s=sp()){
  return x&&Number.isInteger(+x.round)&&/^\d{4}[\/-]\d{1,2}[\/-]\d{1,2}$/.test(x.date||'')&&Array.isArray(x.main)&&x.main.length===s.k&&new Set(x.main.map(Number)).size===s.k&&x.main.every(n=>Number.isInteger(+n)&&+n>=1&&+n<=s.max)&&Array.isArray(x.bonus)&&x.bonus.length===s.b&&new Set(x.bonus.map(Number)).size===s.b&&x.bonus.every(n=>Number.isInteger(+n)&&+n>=1&&+n<=s.max)&&x.bonus.every(n=>!x.main.map(Number).includes(+n));
}
async function syncAuto(show=true){
  const base=apiBase();
  if(!base){ if(show) $('#syncStatus').textContent='自動取得APIが未設定です'; return false; }
  const st=show?$('#syncStatus'):null;
  if(st) st.textContent='最新結果を確認中…';
  try{
    const res=await fetch(`${base}/api/results?game=${game}`,{cache:'no-store'});
    if(!res.ok) throw new Error(`HTTP ${res.status}`);
    const data=await res.json();
    const list=(data.results||[]).filter(x=>validateDraw(x));
    if(!list.length) throw new Error(data.message||'有効な結果がありません');
    const ex=get('extra',[]), map=new Map(ex.map(x=>[x.round,x]));
    let added=0,updated=0;
    for(const x of list){
      const n={round:+x.round,date:(x.date||'').replaceAll('-','/'),main:x.main.map(Number).sort((a,b)=>a-b),bonus:x.bonus.map(Number).sort((a,b)=>a-b)};
      const old=map.get(n.round);
      if(!old){map.set(n.round,n);added++}
      else if(JSON.stringify(old)!==JSON.stringify(n)){map.set(n.round,n);updated++}
    }
    put('extra',[...map.values()].sort((a,b)=>a.round-b));
    merge(); latest(); gen(); rate(); history();
    const src=data.sourceLabel||data.source||'自動取得';
    if(st) st.textContent=`自動取得完了：追加${added}件・更新${updated}件（${src}）`;
    localStorage.setItem(`${game}-last-auto-sync`,new Date().toISOString());
    return true;
  }catch(e){
    if(st) st.textContent=`自動取得失敗：${e.message}`;
    console.error(e); return false;
  }
}
function renderApiSetting(){ const el=$('#apiUrl'); if(el) el.value=apiBase(); }

const sp=()=>SPECS[game],key=x=>`${game}-${x}`;
function get(k,d){try{return JSON.parse(localStorage.getItem(key(k))||JSON.stringify(d))}catch{return d}}
function put(k,v){localStorage.setItem(key(k),JSON.stringify(v))}
function cfg(){return {...DEFAULT_ON,...get('filters',{})}}function weights(){return {...DEFAULT_W,...get('weights',{})}}
function parseCSV(t,g){const ls=t.replace(/^\uFEFF/,'').trim().split(/\r?\n/),s=SPECS[g];return ls.slice(1).map(l=>{const c=l.split(',');return{round:+c[0],date:c[1],main:c.slice(2,2+s.k).map(Number).sort((a,b)=>a-b),bonus:c.slice(2+s.k,2+s.k+s.b).map(Number)}}).filter(x=>x.round&&x.main.length===s.k&&x.main.every(Number.isFinite))}
function merge(){const m=new Map();[...(base[game]||[]),...get('extra',[])].forEach(x=>m.set(x.round,x));rows=[...m.values()].sort((a,b)=>a.round-b)}
function balls(a,b=false){return `<div class="balls">${a.map(n=>`<span class="ball ${b?'bonus':''}">${fmt(n)}</span>`).join('')}</div>`}
function odd(a){return a.filter(n=>n%2).length}function con(a){let c=0;for(let i=1;i<a.length;i++)if(a[i]-a[i-1]===1)c++;return c}function tail(a){const z={};a.forEach(n=>z[n%10]=(z[n%10]||0)+1);return Object.values(z).reduce((s,v)=>s+Math.max(0,v-1),0)}
function slide(a,p){const q=new Set(p.flatMap(n=>[n-1,n+1]).filter(n=>n>=1&&n<=sp().max));return a.filter(n=>q.has(n)).length}function zoneCounts(a){return sp().zones.map(([l,h])=>a.filter(n=>n>=l&&n<=h).length)}
function features(a,h){const p=h.at(-1)?.main||[],recent=h.slice(-20),freq=Array(sp().max+1).fill(0);recent.forEach(r=>r.main.forEach(n=>freq[n]++));const last=Array(sp().max+1).fill(999);for(let i=h.length-1;i>=0;i--)for(const n of h[i].main)if(last[n]===999)last[n]=h.length-1-i;const o=odd(a),sm=a.reduce((x,y)=>x+y,0),ov=a.filter(n=>p.includes(n)).length,sl=slide(a,p),z=zoneCounts(a),td=tail(a);return{odd:(o===Math.floor(sp().k/2)||o===Math.ceil(sp().k/2))?1:([2,sp().k-2].includes(o)?.45:0),sum:sm>=sp().sum[0]&&sm<=sp().sum[1]?1:(sm>=sp().sumSoft[0]&&sm<=sp().sumSoft[1]?.4:0),con:con(a)<=1?1:(con(a)===2?.25:0),tail:td>=1&&td<=2?1:(td===0?.35:0),zones:z.filter(v=>v>0).length>=3?1:.2,overlap:ov<=2?1:0,slide:sl>=1&&sl<=3?1:(sl===0?.25:0),hot:a.reduce((s,n)=>s+freq[n],0)/(Math.max(1,recent.length)*sp().k/sp().max),high:a.some(n=>n>=sp().high)?1:0,cold:a.filter(n=>last[n]>=12&&last[n]<999).length<=1?1:.2}}
function score(a,h,c=cfg(),w=weights()){const f=features(a,h);return Object.keys(DEFAULT_ON).reduce((s,k)=>s+(c[k]?w[k]*(f[k]||0):0),0)}
function rng(seed){return()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}}
function generateAt(h,seed,count=900,c=cfg(),w=weights()){const r=rng(seed),cand=[];for(let i=0;i<count;i++){const q=new Set();while(q.size<sp().k)q.add(1+Math.floor(r()*sp().max));const a=[...q].sort((x,y)=>x-y);cand.push({a,s:score(a,h,c,w)})}cand.sort((a,b)=>b.s-a.s);const out=[],os=[],use={};while(out.length<5&&cand.length){let bi=0,bv=-1e9;for(let i=0;i<Math.min(260,cand.length);i++){const x=cand[i],mx=out.length?Math.max(...out.map(p=>p.filter(n=>x.a.includes(n)).length)):0,v=x.s-x.a.reduce((s,n)=>s+(use[n]||0)*6,0)-Math.max(0,mx-3)*22;if(v>bv){bv=v;bi=i}}const x=cand.splice(bi,1)[0];out.push(x.a);os.push(x.s);x.a.forEach(n=>use[n]=(use[n]||0)+1)}return{sets:out,scores:os}}
function latest(){const x=rows.at(-1);$('#latest').innerHTML=x?`<h3>第${x.round}回　${x.date}</h3>${balls(x.main)}<h3>ボーナス</h3>${balls(x.bonus,true)}`:'データなし';$('#dataStatus').textContent=`${sp().name} 登録済み ${rows.length}回分`;$('#round').value=(x?.round||0)+1;$('#mainLabel').textContent=`本数字${sp().k}個`;$('#bonusLabel').textContent=`ボーナス${sp().b}個`;$('#mainNums').placeholder=Array.from({length:sp().k},(_,i)=>i+1).join(' ');$('#bonusNums').placeholder=sp().b===1?'43':'23 36'}
function gen(){const g=generateAt(rows,(rows.at(-1)?.round||1)*7919+Date.now()%99991,9000);sets=g.sets;scores=g.scores;$('#predictions').innerHTML=sets.map((a,i)=>`<div class="set"><div class="sethead"><span class="tag">${'ABCDE'[i]}セット</span><span class="score">適合度 ${scores[i].toFixed(1)}</span></div>${balls(a)}</div>`).join('')}
function renderSwitch(){const c=cfg();$('#filterSwitches').innerHTML=Object.keys(DEFAULT_ON).map(k=>`<label class="switch"><input type="checkbox" data-filter="${k}" ${c[k]?'checked':''}>${FN[k]}</label>`).join('')}
function renderWeights(){const w=weights(),mx=Math.max(...Object.values(w));$('#weightSummary').innerHTML=Object.keys(w).map(k=>`<div class="small" style="display:grid;grid-template-columns:110px 1fr 38px;gap:7px;align-items:center;margin:7px 0"><span>${FN[k]}</span><span class="bar"><i style="width:${w[k]/mx*100}%"></i></span><b>${w[k].toFixed(1)}</b></div>`).join('')}
function rate(n=0){const d=n?rows.slice(-n):rows,out={};Object.keys(DEFAULT_ON).forEach(k=>out[k]=0);d.forEach((r,j)=>{const idx=rows.findIndex(x=>x.round===r.round),f=features(r.main,rows.slice(0,idx));Object.keys(out).forEach(k=>{if(f[k]>=.75)out[k]++})});$('#filterRates').innerHTML=`<table><tr><th>条件</th><th>通過率</th></tr>${Object.keys(out).map(k=>`<tr><td>${FN[k]}</td><td>${d.length?(out[k]/d.length*100).toFixed(1):0}%</td></tr>`).join('')}</table>`}
function match(a,b){const s=new Set(b);return a.filter(x=>s.has(x)).length}
async function backtest(n,c=cfg(),w=weights(),quiet=false){stopBT=false;const end=rows.length,start=n?Math.max(30,end-n):30,R=[];for(let i=start;i<end;i++){if(stopBT)break;const g=generateAt(rows.slice(0,i),rows[i].round*7919,320,c,w),ms=g.sets.map(s=>match(s,rows[i].main)),u=new Set(g.sets.flat());R.push({max:Math.max(...ms),avg:ms.reduce((a,b)=>a+b,0)/5,cover:rows[i].main.filter(x=>u.has(x)).length});if(!quiet&&(i-start)%5===0){$('#btStatus').textContent=`${i-start+1}/${end-start}回を検証中`;await new Promise(r=>setTimeout(r,0))}}if(!R.length)return null;const A=k=>R.reduce((s,x)=>s+x[k],0)/R.length,P=k=>R.filter(x=>x.max>=k).length/R.length*100,D=Array.from({length:sp().k+1},(_,k)=>R.filter(x=>x.max===k).length),o={count:R.length,avg:A('avg'),max:A('max'),cover:A('cover'),p3:P(3),p4:P(4),p5:P(5),dist:D};if(!quiet){$('#btStatus').textContent=`${o.count}回完了`;$('#btResult').innerHTML=`<div class="grid"><div class="metric"><b>${o.avg.toFixed(3)}</b><span>1口平均一致</span></div><div class="metric"><b>${o.max.toFixed(3)}</b><span>5口最高一致平均</span></div><div class="metric"><b>${o.cover.toFixed(2)}</b><span>5口カバー</span></div><div class="metric"><b>${o.p4.toFixed(1)}%</b><span>4個以上</span></div></div><table><tr><td>3個以上</td><td>${o.p3.toFixed(1)}%</td></tr><tr><td>5個以上</td><td>${o.p5.toFixed(2)}%</td></tr></table>`;chart(D)}return o}
function chart(d){const c=$('#btChart'),x=c.getContext('2d'),w=c.width,h=c.height;x.clearRect(0,0,w,h);const m=Math.max(...d,1),bw=w/(d.length+1);x.fillStyle='#647168';x.font='22px sans-serif';d.forEach((v,i)=>{const bh=(h-65)*v/m;x.fillRect((i+.55)*bw,h-35-bh,bw*.55,bh);x.fillText(i,(i+.72)*bw,h-8);x.fillText(v,(i+.58)*bw,h-42-bh)})}
function baseline(){const mean=sp().k*sp().k/sp().max;$('#baseline').innerHTML=`<div class="metric"><b>${mean.toFixed(3)}</b><span>ランダム1口の理論平均一致</span></div><p class="note">過去成績は将来の優位性を保証しません。</p>`}
async function ablation(){const b=await backtest(100,cfg(),weights(),true),out=[];for(const k of Object.keys(DEFAULT_ON)){const c={...cfg(),[k]:false};$('#ablationStatus').textContent=`${FN[k]}を検証中`;const r=await backtest(100,c,weights(),true);out.push({k,d:r.max-b.max});await new Promise(r=>setTimeout(r,0))}out.sort((a,b)=>a.d-b.d);$('#ablationStatus').textContent='完了';$('#ablationResult').innerHTML=`<table><tr><th>外した条件</th><th>変化</th><th>判定</th></tr>${out.map(x=>`<tr><td>${FN[x.k]}</td><td>${x.d>=0?'+':''}${x.d.toFixed(3)}</td><td>${x.d<-.01?'維持候補':x.d>.01?'弱める候補':'影響小'}</td></tr>`).join('')}</table>`}
async function tune(){const w={...weights()};$('#tuneStatus').textContent='標準成績を計算中';let best=await backtest(100,cfg(),w,true);for(const k of Object.keys(w)){for(const mul of [.75,1.25]){const t={...w,[k]:Math.max(0.5,w[k]*mul)};$('#tuneStatus').textContent=`${FN[k]}を調整中`;const r=await backtest(100,cfg(),t,true);if(r.max>best.max+.004||(Math.abs(r.max-best.max)<.004&&r.cover>best.cover+.02)){w[k]=t[k];best=r}await new Promise(r=>setTimeout(r,0))}}put('weights',w);renderWeights();gen();$('#tuneStatus').textContent=`調整完了：最高一致平均 ${best.max.toFixed(3)}`}
function history(){const hs=get('history',[]);$('#history').innerHTML=hs.length?hs.map(h=>{const r=rows.find(x=>x.round===h.round),ms=r?h.sets.map(s=>match(s,r.main)):null;return `<div class="set"><div class="sethead"><b>第${h.round}回</b><span>${ms?`最高${Math.max(...ms)}個一致`:'結果待ち'}</span></div>${h.sets.map((s,i)=>`<div class="small">${'ABCDE'[i]}：${s.map(fmt).join('・')}${ms?`（${ms[i]}個）`:''}</div>`).join('')}</div>`}).join(''):'<p class="note">保存履歴はありません。</p>'}
function save(){const r=(rows.at(-1)?.round||0)+1,h=get('history',[]).filter(x=>x.round!==r);h.unshift({round:r,saved:new Date().toISOString(),sets,scores});put('history',h.slice(0,150));history();alert(`第${r}回向けとして保存しました`)}
function nums(s){return s.split(/[\s,、・]+/).filter(Boolean).map(Number)}
async function load(){if(!base[game])base[game]=parseCSV(await fetch(sp().file).then(r=>r.text()),game);merge();latest();gen();renderSwitch();renderWeights();rate();baseline();history();renderApiSetting();$$('[data-game]').forEach(b=>b.classList.toggle('active',b.dataset.game===game));document.title=`LOTO AI ${sp().name} Ver.14`;if(apiBase())syncAuto(false)}
async function changeGame(g){game=g;localStorage.setItem('loto-game',g);await load()}
$$('[data-game]').forEach(b=>b.onclick=()=>changeGame(b.dataset.game));$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.page').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.page).classList.add('active')});
$$('.backtest').forEach(b=>b.onclick=()=>backtest(+b.dataset.n));$$('.period').forEach(b=>b.onclick=()=>rate(+b.dataset.n));$('#stopBacktest').onclick=()=>stopBT=true;$('#regen').onclick=gen;$('#savePrediction').onclick=save;$('#copySets').onclick=()=>navigator.clipboard.writeText(sets.map((a,i)=>`${'ABCDE'[i]}：${a.map(fmt).join('・')}`).join('\n')).then(()=>alert('コピーしました'));$('#applyFilters').onclick=()=>{const c={};$$('[data-filter]').forEach(x=>c[x.dataset.filter]=x.checked);put('filters',c);gen()};$('#resetFilters').onclick=()=>{localStorage.removeItem(key('filters'));renderSwitch();gen()};$('#ablationBtn').onclick=ablation;$('#autoTune').onclick=tune;$('#resetWeights').onclick=()=>{localStorage.removeItem(key('weights'));renderWeights();gen()};$('#official').onclick=()=>open(sp().official,'_blank');
$('#syncNow').onclick=()=>syncAuto(true);$('#apiSettings').onclick=()=>{document.querySelector('[data-page=add]').click();setTimeout(()=>$('#apiUrl').focus(),100)};$('#saveApi').onclick=async()=>{const u=$('#apiUrl').value.trim().replace(/\/$/,'');if(!/^https:\/\//.test(u)){ $('#apiMsg').textContent='https://から始まるURLを入力してください';return}localStorage.setItem(API_STORAGE,u);$('#apiMsg').textContent='保存しました。接続確認中…';const ok=await syncAuto(true);$('#apiMsg').textContent=ok?'接続確認に成功しました':'接続できません。Worker URLを確認してください'};$('#clearApi').onclick=()=>{localStorage.removeItem(API_STORAGE);$('#apiUrl').value='';$('#apiMsg').textContent='設定を解除しました'};
$('#addResult').onclick=()=>{const r=+$('#round').value,d=$('#date').value,m=nums($('#mainNums').value),b=nums($('#bonusNums').value);if(!r||!d||m.length!==sp().k||b.length!==sp().b||new Set(m).size!==sp().k||m.some(n=>n<1||n>sp().max)||b.some(n=>n<1||n>sp().max)){ $('#addMsg').textContent='入力内容を確認してください';return}const ex=get('extra',[]).filter(x=>x.round!==r);ex.push({round:r,date:d.replaceAll('-','/'),main:m.sort((a,b)=>a-b),bonus:b.sort((a,b)=>a-b)});put('extra',ex);merge();latest();gen();rate();history();$('#round').value=r+1;$('#addMsg').textContent=`第${r}回を保存・照合しました`};
$('#exportBtn').onclick=()=>{const data={game,all:{loto6:{extra:getFor('loto6','extra'),history:getFor('loto6','history'),filters:getFor('loto6','filters'),weights:getFor('loto6','weights')},loto7:{extra:getFor('loto7','extra'),history:getFor('loto7','history'),filters:getFor('loto7','filters'),weights:getFor('loto7','weights')}}},blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='loto_ai_ver14_backup.json';a.click()};function getFor(g,k){try{return JSON.parse(localStorage.getItem(`${g}-${k}`)||'null')}catch{return null}}
$('#importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=async()=>{try{const d=JSON.parse(rd.result);for(const g of ['loto6','loto7'])for(const k of ['extra','history','filters','weights'])if(d.all?.[g]?.[k]!=null)localStorage.setItem(`${g}-${k}`,JSON.stringify(d.all[g][k]));await load();alert('読み込みました')}catch{alert('読み込みに失敗しました')}};rd.readAsText(f)};$('#resetBtn').onclick=()=>{if(confirm(`${sp().name}の手入力データを削除しますか？`)){localStorage.removeItem(key('extra'));merge();latest();gen();rate();history()}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});load().catch(e=>{$('#dataStatus').textContent='データ読込失敗';console.error(e)});
