const config={loto6:{name:"ロト6",max:43,pick:6,bonus:1,file:"loto6.json"},loto7:{name:"ロト7",max:37,pick:7,bonus:2,file:"loto7.json"}};
const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)];let game="loto6",draws={};let user=JSON.parse(localStorage.getItem("loto67v6")||localStorage.getItem("loto67v4")||'{"loto6":{"sets":[],"checks":[]},"loto7":{"sets":[],"checks":[]}}');const C=()=>config[game],R=()=>draws[game];
async function loadJson(path){const r=await fetch(path,{cache:"no-store"});if(!r.ok)throw new Error(`${path}: HTTP ${r.status}`);const data=await r.json();if(!Array.isArray(data)||!data.length)throw new Error(`${path}: データ形式エラー`);return data}
async function boot(){try{draws.loto6=await loadJson(config.loto6.file);draws.loto7=await loadJson(config.loto7.file);bind();render();if("serviceWorker" in navigator)navigator.serviceWorker.register("service-worker.js").catch(()=>{})}catch(e){console.error(e);document.body.innerHTML=`<main><div class="card"><h2>データを読み込めませんでした</h2><p>${String(e.message||e)}</p><p>GitHub直下に index.html、app.js、app.css、loto6.json、loto7.json があるか確認してください。</p><button onclick="location.reload()" class="primary">再読み込み</button></div></main>`}}
function bind(){$$("[data-game]").forEach(b=>b.onclick=()=>{game=b.dataset.game;$$("[data-game]").forEach(x=>x.classList.toggle("active",x===b));document.body.classList.toggle("loto7",game==="loto7");render()});$$("[data-tab]").forEach(b=>b.onclick=()=>{$$("[data-tab]").forEach(x=>x.classList.remove("active"));b.classList.add("active");$$("section").forEach(s=>s.classList.remove("active"));$("#"+b.dataset.tab).classList.add("active");if(b.dataset.tab==="report")renderReport()});$("#analysisWindow").onchange=renderAnalysis;$("#reportWindow").onchange=renderReport;$("#generateBtn").onclick=generate;$("#saveSetsBtn").onclick=()=>{save();alert("購入セットとして保存しました")};$("#validateBtn").onclick=validate;$("#historySearch").oninput=renderHistory;$("#exportBtn").onclick=exportData;$("#importBtn").onclick=importData;$("#copyReportBtn").onclick=copyReport;let prompt;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();prompt=e;$("#installBtn").hidden=false});$("#installBtn").onclick=async()=>{if(prompt){prompt.prompt();await prompt.userChoice;prompt=null;$("#installBtn").hidden=true}}}
function save(){localStorage.setItem("loto67v6",JSON.stringify(user))}function balls(a){return `<div class="balls">${a.map(n=>`<span class="ball">${String(n).padStart(2,"0")}</span>`).join("")}</div>`}function parse(v){return v.split(/[,\s、・]+/).map(Number).filter(Boolean).sort((a,b)=>a-b)}function rowsFor(v){return v==="all"?R():R().slice(-Number(v))}
function stats(v){let rows=rowsFor(v),count=Array(C().max+1).fill(0);rows.forEach(r=>r.nums.forEach(n=>count[n]++));let rank=[];for(let n=1;n<=C().max;n++){let i=[...rows].reverse().findIndex(r=>r.nums.includes(n));rank.push({n,c:count[n],gap:i<0?rows.length:i})}rank.sort((a,b)=>b.c-a.c||a.gap-b.gap);return{rows,rank,count}}
function render(){let c=C(),r=R(),last=r.at(-1);$("#dashboardTitle").textContent=c.name+" ダッシュボード";$("#drawCount").textContent=r.length+"回";$("#latestNo").textContent="第"+last.no+"回";$("#latestDate").textContent=last.date;$("#numberRange").textContent="1～"+c.max;$("#latestBalls").innerHTML=balls(last.nums);$("#latestBonus").textContent="ボーナス："+last.bonus.join("・");$("#winningLabel").textContent=`本数字（${c.pick}個）`;$("#bonusLabel").textContent=`ボーナス数字（${c.bonus}個）`;renderAnalysis();renderSets();renderValidationHistory();renderHistory();renderReport()}
function renderAnalysis(){let o=stats($("#analysisWindow").value),rows=o.rows,max=o.rank[0].c,min=Math.min(...o.rank.map(x=>x.c));$("#hotNumber").textContent=o.rank[0].n+"（"+max+"）";$("#coldNumber").textContent=o.rank.filter(x=>x.c===min).slice(0,4).map(x=>x.n).join("・");$("#averageSum").textContent=(rows.reduce((a,r)=>a+r.nums.reduce((x,y)=>x+y,0),0)/rows.length).toFixed(1);$("#averageOdd").textContent=(rows.reduce((a,r)=>a+r.nums.filter(n=>n%2).length,0)/rows.length).toFixed(2);$("#rankingBody").innerHTML=o.rank.map((x,i)=>`<tr><td>${i+1}</td><td><b>${x.n}</b></td><td>${x.c}</td><td>${x.gap}</td><td><div class="bar"><i style="width:${x.c/max*100}%"></i></div></td></tr>`).join("")}
function scoreNumbers(windowValue){let o=stats(windowValue),latest=R().at(-1),score={};o.rank.forEach(x=>score[x.n]=(x.c/o.rows.length)*14+Math.min(x.gap,18)*.10+(latest.nums.includes(x.n)?.35:0));return{score,o}}
function generate(){let {score}=scoreNumbers($("#predictionWindow").value),pool=Object.keys(score).map(Number).sort((a,b)=>score[b]-score[a]).slice(0,C().pick===6?30:28),sets=[];for(let k=0;k<5;k++){let chosen=[];for(let n of pool){if(chosen.length===C().pick)break;let maxOverlap=C().pick===6?2:3;if(sets.some(s=>s.filter(v=>chosen.includes(v)||v===n).length>maxOverlap))continue;chosen.push(n)}if(chosen.length<C().pick){for(let n of pool)if(!chosen.includes(n)&&chosen.length<C().pick)chosen.push(n)}sets.push(chosen.sort((a,b)=>a-b));pool.push(pool.shift())}user[game].sets=sets;save();renderSets();renderReport()}
function acValue(a){let d=new Set;for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length;j++)d.add(a[j]-a[i]);return d.size-(a.length-1)}
function setMetrics(a){let sum=a.reduce((x,y)=>x+y,0),odd=a.filter(n=>n%2).length,consecutive=0;for(let i=1;i<a.length;i++)if(a[i]===a[i-1]+1)consecutive++;return{sum,odd,consecutive,ac:acValue(a),range:a.at(-1)-a[0]}}
function renderSets(){let sets=user[game].sets;$("#predictionSets").innerHTML=sets.length?sets.map((a,i)=>{let m=setMetrics(a);return `<div class="set"><div class="settop"><b>第${i+1}口</b><span class="badge">合計 ${m.sum}</span></div>${balls(a)}<div class="mini-metrics">奇数 ${m.odd}｜連番 ${m.consecutive}｜AC ${m.ac}｜幅 ${m.range}</div></div>`}).join(""):"<p class='muted'>5セットを生成してください。</p>"}
function validate(){let nums=parse($("#winningInput").value),bonus=parse($("#bonusInput").value),no=Number($("#validationNo").value);if(nums.length!==C().pick||new Set(nums).size!==C().pick)return alert("本数字の個数を確認してください");if(bonus.length!==C().bonus)return alert("ボーナス数字の個数を確認してください");if(nums.some(n=>n<1||n>C().max)||bonus.some(n=>n<1||n>C().max))return alert("数字の範囲を確認してください");let m=user[game].sets.map(s=>s.filter(n=>nums.includes(n)).length),highest=m.length?Math.max(...m):0;user[game].checks.unshift({no,nums,bonus,highest,date:new Date().toISOString()});save();$("#validationResult").innerHTML=`<div class="card"><h3>最高一致 ${highest}個</h3>${m.map((v,i)=>`<p>第${i+1}口：${v}個一致</p>`).join("")}</div>`;renderValidationHistory()}
function renderValidationHistory(){$("#validationHistory").innerHTML=user[game].checks.map(x=>`<tr><td>${x.no||"-"}</td><td>${x.highest}</td><td>${x.nums.join("・")}</td></tr>`).join("")||'<tr><td colspan="3">履歴なし</td></tr>'}
function renderHistory(){let q=$("#historySearch").value.trim(),rows=[...R()].reverse();if(q){let n=Number(q);rows=rows.filter(r=>r.no===n||r.nums.includes(n)||r.bonus.includes(n))}$("#historyBody").innerHTML=rows.slice(0,600).map(r=>`<tr><td>${r.no}</td><td>${r.date}</td><td>${r.nums.join("・")}</td><td>${r.bonus.join("・")}</td></tr>`).join("")}
function reportText(){let v=$("#reportWindow")?.value||"100",o=stats(v),rows=o.rows,top=o.rank.slice(0,7).map(x=>x.n),late=[...o.rank].sort((a,b)=>b.gap-a.gap).slice(0,7).map(x=>x.n),sums=rows.map(r=>r.nums.reduce((a,b)=>a+b,0)),avg=sums.reduce((a,b)=>a+b,0)/sums.length,sd=Math.sqrt(sums.reduce((a,b)=>a+(b-avg)**2,0)/sums.length),odd=rows.reduce((a,r)=>a+r.nums.filter(n=>n%2).length,0)/rows.length;return `${C().name} ${v==="all"?"全期間":"直近"+v+"回"}分析\n最多出現上位: ${top.join("・")}\n長期間隔上位: ${late.join("・")}\n本数字合計: 平均 ${avg.toFixed(1)} / 標準偏差 ${sd.toFixed(1)}\n奇数個数平均: ${odd.toFixed(2)}\n注意: これは過去履歴の統計要約であり、各組み合わせの理論上の当選確率を変えるものではありません。`}
function renderReport(){if(!$("#aiReport"))return;let text=reportText();$("#aiReport").innerHTML=`<div class="report-box">${text.split("\n").map(x=>`<p>${x}</p>`).join("")}</div>`;let sets=user[game].sets;$("#setEvaluation").innerHTML=sets.length?sets.map((s,i)=>{let m=setMetrics(s);let score=100-Math.abs(m.odd-C().pick/2)*8-m.consecutive*5-Math.max(0,Math.abs(m.range-(C().max*.72))*.5);score=Math.max(0,Math.min(100,Math.round(score)));return `<div class="eval-row"><b>第${i+1}口</b><span>${score} / 100</span><div class="bar"><i style="width:${score}%"></i></div><small>合計 ${m.sum}・奇数 ${m.odd}・連番 ${m.consecutive}・AC ${m.ac}</small></div>`}).join(""):"<p class='muted'>予想セット生成後に構造評価を表示します。</p>"}
async function copyReport(){try{await navigator.clipboard.writeText(reportText());alert("レポートをコピーしました")}catch{alert("コピーできませんでした")}}
function exportData(){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(user,null,2)],{type:"application/json"}));a.download="loto67_user_data_v6.json";a.click()}function importData(){try{let x=JSON.parse($("#importText").value);if(!x.loto6||!x.loto7)throw Error();user=x;save();render();alert("読み込みました")}catch{alert("JSON形式を確認してください")}}
boot();
